name               = "structout"
main               = "src/worker.ts"
compatibility_date = "2025-06-19"

[assets]
directory = "./dist"        # Vite build output

[build]
command  = "pnpm run build"


[vars]                       # passed to Vite at build
VITE_CF_SITE_KEY = "0x4AAAAAABSR5TfFVPaT76uB"
